# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "vmware_desktop" do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # CentOS 7 server
  config.vm.define "server" do |server|
    server.vm.hostname = "server.test"
  end

end
