# ---
# dependency:
#   name: galaxy
# driver:
#   name: docker
# platforms:
#   - name: instance
#     image: docker.io/pycontribs/centos:7
#     pre_build_image: true
# provisioner:
#   name: ansible
# verifier:
#   name: ansible

---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
verifier:
  name: ansible
