# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base configuration
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Define Ubuntu server
  config.vm.define "ubuntu-server" do |srv1|
    srv1.vm.box = "generic/ubuntu1604"
    srv1.vm.network :private_network, ip: "192.168.229.131"
    srv1.vm.hostname = "server-u.test"
    srv1.vm.provider "vmware_desktop" do |v|
      v.memory = 512
      v.linked_clone = true
    end
  end

  # Define CentOS server
  config.vm.define "centos-server" do |srv2|
    srv2.vm.box = "generic/centos7"
    srv2.vm.network :private_network, ip: "192.168.229.132"
    srv2.vm.hostname = "server-c.test"
    srv2.vm.provider "vmware_desktop" do |v|
      v.memory = 512
      v.linked_clone = true
    end
  end

end
