---
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
          - debian10

    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v4
      
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Ensure compatible Python version

      - name: Install test dependencies.
        run: pip install ansible==8.7.0 molecule-plugins==23.5.3 docker==7.1.0 yamllint==1.35.1 ansible-lint==6.22.2 requests==2.31.0

      - name: Execute Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
