---
- name: Ensure Apache is installed
  package:
    name: "{{ apache_package }}"
    state: present
    update_cache: yes
  # register: apt_result
  # until: apt_result is succeeded

- name: Copy test config file
  copy:
    src: files/test.conf
    dest: "{{ apache_config_dir }}/test.conf"
  notify:
    - restart apache

- name: Ensure Apache is running and starts at boot
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true