---
- hosts: solr
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt: 
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: Restart solr
      service: name=solr state=restart

  tasks:
    - name: Install Java.
      apt: 
        name: openjdk-8-jdk
        state: present

    - name: Download Solr.
      get_url:
        url: "https://mirrors.ocf.berkeley.edu/apache/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"
        validate_certs: false

    - name: Expand Solr.
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

    - name: Run Solr installation script.
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
      args:
        creates: "{{ solr_dir }}/bin/solr"

    - name: Ensure solr is started and enabled at boot.
      service:
        name: solr
        state: started
        enabled: true